print("hello")
mylist=["apple","mango","banana","pineapple","jackfruit"]
print(mylist[1])
print(mylist[-1])
print(len(mylist))
mylist.append("dragon fruit")
print(mylist)
mylist.remove("pineapple")
print(mylist)
mylist.sort()
print(mylist)
mylist.reverse()
print(mylist)
mylist.clear()
print(mylist)